#!/usr/bin/env php
<?php

if (!defined('STDIN'))
{
  die('This tool is designed to be run from the command line.'."\n");
}

if(!extension_loaded('pdo_sqlite'))
{
  die('You need the pdo_sqlite PHP extension to run the tests'."\n");
}

chdir(dirname(__FILE__).'/dmCorePlugin/test/project');

$_SERVER['argv'] = array(
  $_SERVER['argv'][0],
  'test:all'
);

require_once dirname(__FILE__).'/symfony/lib/command/cli.php';

return 0;