<?php

/**
 * PluginDmLayout
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5845 2009-06-09 07:36:57Z jwage $
 */
abstract class PluginDmLayout extends BaseDmLayout
{
  protected static
  $areaTypes = array('top', 'bottom', 'left', 'right');

  public static function getAreaTypes()
  {
    return self::$areaTypes;
  }

  public function getArea($type)
  {
    if (!in_array($type, self::getAreaTypes()))
    {
      throw new dmException(sprintf('%s is not a valid area type. These are : %s', $type, implode(', ', self::getAreaTypes())));
    }

    foreach($this->get('Areas') as $area)
    {
      if($area->get('type') == $type)
      {
        return $area;
      }
    }

    return null;
  }

  public function save(Doctrine_Connection $conn = null)
  {
    $return = parent::save($conn);

    foreach(self::getAreaTypes() as $type)
    {
      if (!$this->getArea($type))
      {
        $this->Areas[] = dmDb::create('DmArea', array(
          'dm_layout_id' => $this->id,
          'type' => $type
        ))->saveGet();
      }
    }

    return $return;
  }

}