<?php

/**
 * DmRecordPermissionUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DmRecordPermissionUserTable extends PluginDmRecordPermissionUserTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object DmRecordPermissionUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DmRecordPermissionUser');
    }
}