<?php

/**
 * BaseDmContact
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $email
 * @property clob $body
 * 
 * @method string    getName()  Returns the current record's "name" value
 * @method string    getEmail() Returns the current record's "email" value
 * @method clob      getBody()  Returns the current record's "body" value
 * @method DmContact setName()  Sets the current record's "name" value
 * @method DmContact setEmail() Sets the current record's "email" value
 * @method DmContact setBody()  Sets the current record's "body" value
 * 
 * @package    retest
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDmContact extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dm_contact');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('body', 'clob', null, array(
             'type' => 'clob',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}