<?php

/**
 * PluginDmSetting
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5925 2009-06-22 21:27:17Z jwage $
 */
abstract class PluginDmSetting extends BaseDmSetting
{

  public function preSave($event)
  {
    parent::preSave($event);
    
    $this->name = dmString::underscore($this->name);
    
    if(!$this->value && $this->setting_default)
    {
      $this->value = $this->setting_default;
    }
  }
  
}