<?php

/**
 * BaseComment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $post_id
 * @property string $author
 * @property clob $body
 * @property Post $Post
 * 
 * @method integer getPostId()  Returns the current record's "post_id" value
 * @method string  getAuthor()  Returns the current record's "author" value
 * @method clob    getBody()    Returns the current record's "body" value
 * @method Post    getPost()    Returns the current record's "Post" value
 * @method Comment setPostId()  Sets the current record's "post_id" value
 * @method Comment setAuthor()  Sets the current record's "author" value
 * @method Comment setBody()    Sets the current record's "body" value
 * @method Comment setPost()    Sets the current record's "Post" value
 * 
 * @package    retest
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseComment extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('comment');
        $this->hasColumn('post_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('author', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('body', 'clob', null, array(
             'type' => 'clob',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Post', array(
             'local' => 'post_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $dmversionable0 = new Doctrine_Template_DmVersionable();
        $this->actAs($timestampable0);
        $this->actAs($dmversionable0);
    }
}