<?php

/**
 * BaseDmTestFruit
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * 
 * @method string      getTitle() Returns the current record's "title" value
 * @method DmTestFruit setTitle() Sets the current record's "title" value
 * 
 * @package    retest
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseDmTestFruit extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dm_test_fruit');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}