<?php

/**
 * BaseDmTestCateg
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property boolean $is_active
 * @property Doctrine_Collection $Domains
 * @property Doctrine_Collection $DmTestDomainCateg
 * @property Doctrine_Collection $Posts
 * 
 * @method string              getTitle()             Returns the current record's "title" value
 * @method boolean             getIsActive()          Returns the current record's "is_active" value
 * @method Doctrine_Collection getDomains()           Returns the current record's "Domains" collection
 * @method Doctrine_Collection getDmTestDomainCateg() Returns the current record's "DmTestDomainCateg" collection
 * @method Doctrine_Collection getPosts()             Returns the current record's "Posts" collection
 * @method DmTestCateg         setTitle()             Sets the current record's "title" value
 * @method DmTestCateg         setIsActive()          Sets the current record's "is_active" value
 * @method DmTestCateg         setDomains()           Sets the current record's "Domains" collection
 * @method DmTestCateg         setDmTestDomainCateg() Sets the current record's "DmTestDomainCateg" collection
 * @method DmTestCateg         setPosts()             Sets the current record's "Posts" collection
 * 
 * @package    retest
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
abstract class BaseDmTestCateg extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dm_test_categ');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('DmTestDomain as Domains', array(
             'refClass' => 'DmTestDomainCateg',
             'local' => 'categ_id',
             'foreign' => 'domain_id'));

        $this->hasMany('DmTestDomainCateg', array(
             'local' => 'id',
             'foreign' => 'categ_id'));

        $this->hasMany('DmTestPost as Posts', array(
             'local' => 'id',
             'foreign' => 'categ_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sortable0 = new Doctrine_Template_Sortable();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'title',
              1 => 'is_active',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($sortable0);
        $this->actAs($i18n0);
    }
}