<?php

/**
 * BasePost
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $excerpt
 * @property clob $body
 * @property integer $image_id
 * @property DmMedia $Image
 * @property Doctrine_Collection $Comments
 * 
 * @method string              getTitle()    Returns the current record's "title" value
 * @method string              getExcerpt()  Returns the current record's "excerpt" value
 * @method clob                getBody()     Returns the current record's "body" value
 * @method integer             getImageId()  Returns the current record's "image_id" value
 * @method DmMedia             getImage()    Returns the current record's "Image" value
 * @method Doctrine_Collection getComments() Returns the current record's "Comments" collection
 * @method Post                setTitle()    Sets the current record's "title" value
 * @method Post                setExcerpt()  Sets the current record's "excerpt" value
 * @method Post                setBody()     Sets the current record's "body" value
 * @method Post                setImageId()  Sets the current record's "image_id" value
 * @method Post                setImage()    Sets the current record's "Image" value
 * @method Post                setComments() Sets the current record's "Comments" collection
 * 
 * @package    retest
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BasePost extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('post');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => '255',
             ));
        $this->hasColumn('excerpt', 'string', 800, array(
             'type' => 'string',
             'length' => '800',
             ));
        $this->hasColumn('body', 'clob', null, array(
             'type' => 'clob',
             'extra' => 'markdown',
             ));
        $this->hasColumn('image_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('DmMedia as Image', array(
             'local' => 'image_id',
             'foreign' => 'id'));

        $this->hasMany('Comment as Comments', array(
             'local' => 'id',
             'foreign' => 'post_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sortable0 = new Doctrine_Template_Sortable();
        $dmversionable0 = new Doctrine_Template_DmVersionable();
        $this->actAs($timestampable0);
        $this->actAs($sortable0);
        $this->actAs($dmversionable0);
    }
}