<?php

/**
 * BaseDmTestDomainCateg
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $domain_id
 * @property integer $categ_id
 * @property DmTestDomain $Domain
 * @property DmTestCateg $Categ
 * 
 * @method integer           getDomainId()  Returns the current record's "domain_id" value
 * @method integer           getCategId()   Returns the current record's "categ_id" value
 * @method DmTestDomain      getDomain()    Returns the current record's "Domain" value
 * @method DmTestCateg       getCateg()     Returns the current record's "Categ" value
 * @method DmTestDomainCateg setDomainId()  Sets the current record's "domain_id" value
 * @method DmTestDomainCateg setCategId()   Sets the current record's "categ_id" value
 * @method DmTestDomainCateg setDomain()    Sets the current record's "Domain" value
 * @method DmTestDomainCateg setCateg()     Sets the current record's "Categ" value
 * 
 * @package    retest
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDmTestDomainCateg extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dm_test_domain_categ');
        $this->hasColumn('domain_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('categ_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('DmTestDomain as Domain', array(
             'local' => 'domain_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('DmTestCateg as Categ', array(
             'local' => 'categ_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}