<?php

/**
 * BaseDmTestCateg
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property boolean $is_active
 * @property Doctrine_Collection $DmTestPost
 * 
 * @method string              getTitle()      Returns the current record's "title" value
 * @method boolean             getIsActive()   Returns the current record's "is_active" value
 * @method Doctrine_Collection getDmTestPost() Returns the current record's "DmTestPost" collection
 * @method DmTestCateg         setTitle()      Sets the current record's "title" value
 * @method DmTestCateg         setIsActive()   Sets the current record's "is_active" value
 * @method DmTestCateg         setDmTestPost() Sets the current record's "DmTestPost" collection
 * 
 * @package    retest
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseDmTestCateg extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dm_test_categ');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('DmTestPost', array(
             'local' => 'id',
             'foreign' => 'categ_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sortable0 = new Doctrine_Template_Sortable();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'title',
              1 => 'is_active',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($sortable0);
        $this->actAs($i18n0);
    }
}