<?php

/**
 * BaseDmTestPostTag
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $dm_test_post_id
 * @property integer $dm_test_tag_id
 * @property DmTestPost $Post
 * @property DmTestTag $Tag
 * 
 * @method integer       getDmTestPostId()    Returns the current record's "dm_test_post_id" value
 * @method integer       getDmTestTagId()     Returns the current record's "dm_test_tag_id" value
 * @method DmTestPost    getPost()            Returns the current record's "Post" value
 * @method DmTestTag     getTag()             Returns the current record's "Tag" value
 * @method DmTestPostTag setDmTestPostId()    Sets the current record's "dm_test_post_id" value
 * @method DmTestPostTag setDmTestTagId()     Sets the current record's "dm_test_tag_id" value
 * @method DmTestPostTag setPost()            Sets the current record's "Post" value
 * @method DmTestPostTag setTag()             Sets the current record's "Tag" value
 * 
 * @package    retest
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseDmTestPostTag extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dm_test_post_tag');
        $this->hasColumn('dm_test_post_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('dm_test_tag_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('DmTestPost as Post', array(
             'local' => 'dm_test_post_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('DmTestTag as Tag', array(
             'local' => 'dm_test_tag_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}