<?php

/**
 * BaseDmTestPostTag
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $post_id
 * @property integer $tag_id
 * @property DmTestPost $Post
 * @property DmTestTag $Tag
 * 
 * @method integer       getPostId()  Returns the current record's "post_id" value
 * @method integer       getTagId()   Returns the current record's "tag_id" value
 * @method DmTestPost    getPost()    Returns the current record's "Post" value
 * @method DmTestTag     getTag()     Returns the current record's "Tag" value
 * @method DmTestPostTag setPostId()  Sets the current record's "post_id" value
 * @method DmTestPostTag setTagId()   Sets the current record's "tag_id" value
 * @method DmTestPostTag setPost()    Sets the current record's "Post" value
 * @method DmTestPostTag setTag()     Sets the current record's "Tag" value
 * 
 * @package    retest
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDmTestPostTag extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dm_test_post_tag');
        $this->hasColumn('post_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('tag_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('DmTestPost as Post', array(
             'local' => 'post_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('DmTestTag as Tag', array(
             'local' => 'tag_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}