<?php

/**
 * BaseDmTestTag
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $slug
 * @property Doctrine_Collection $Posts
 * @property Doctrine_Collection $DmTestPostTag
 * 
 * @method string              getName()          Returns the current record's "name" value
 * @method string              getSlug()          Returns the current record's "slug" value
 * @method Doctrine_Collection getPosts()         Returns the current record's "Posts" collection
 * @method Doctrine_Collection getDmTestPostTag() Returns the current record's "DmTestPostTag" collection
 * @method DmTestTag           setName()          Sets the current record's "name" value
 * @method DmTestTag           setSlug()          Sets the current record's "slug" value
 * @method DmTestTag           setPosts()         Sets the current record's "Posts" collection
 * @method DmTestTag           setDmTestPostTag() Sets the current record's "DmTestPostTag" collection
 * 
 * @package    retest
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDmTestTag extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dm_test_tag');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('slug', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('DmTestPost as Posts', array(
             'refClass' => 'DmTestPostTag',
             'local' => 'tag_id',
             'foreign' => 'post_id'));

        $this->hasMany('DmTestPostTag', array(
             'local' => 'id',
             'foreign' => 'tag_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'name',
              1 => 'slug',
             ),
             'length' => 7,
             ));
        $this->actAs($timestampable0);
        $this->actAs($i18n0);
    }
}