<?php

/**
 * BaseDmTestDomain
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property boolean $is_active
 * @property Doctrine_Collection $Categs
 * @property Doctrine_Collection $DmTestDomainCateg
 * 
 * @method string              getTitle()             Returns the current record's "title" value
 * @method boolean             getIsActive()          Returns the current record's "is_active" value
 * @method Doctrine_Collection getCategs()            Returns the current record's "Categs" collection
 * @method Doctrine_Collection getDmTestDomainCateg() Returns the current record's "DmTestDomainCateg" collection
 * @method DmTestDomain        setTitle()             Sets the current record's "title" value
 * @method DmTestDomain        setIsActive()          Sets the current record's "is_active" value
 * @method DmTestDomain        setCategs()            Sets the current record's "Categs" collection
 * @method DmTestDomain        setDmTestDomainCateg() Sets the current record's "DmTestDomainCateg" collection
 * 
 * @package    retest
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDmTestDomain extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dm_test_domain');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('DmTestCateg as Categs', array(
             'refClass' => 'DmTestDomainCateg',
             'local' => 'domain_id',
             'foreign' => 'categ_id'));

        $this->hasMany('DmTestDomainCateg', array(
             'local' => 'id',
             'foreign' => 'domain_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sortable0 = new Doctrine_Template_Sortable();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'title',
              1 => 'is_active',
             ),
             'length' => 7,
             ));
        $dmblameable1 = new Doctrine_Template_DmBlameable();
        $i18n0->addChild($dmblameable1);
        $dmtaggable0 = new Doctrine_Template_DmTaggable();
        $this->actAs($timestampable0);
        $this->actAs($sortable0);
        $this->actAs($i18n0);
        $this->actAs($dmtaggable0);
    }
}