<?php

/**
 * BaseDmTestUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property clob $description
 * @property integer $media_id
 * @property boolean $is_visible
 * @property DmMedia $Media
 * 
 * @method string     getName()        Returns the current record's "name" value
 * @method clob       getDescription() Returns the current record's "description" value
 * @method integer    getMediaId()     Returns the current record's "media_id" value
 * @method boolean    getIsVisible()   Returns the current record's "is_visible" value
 * @method DmMedia    getMedia()       Returns the current record's "Media" value
 * @method DmTestUser setName()        Sets the current record's "name" value
 * @method DmTestUser setDescription() Sets the current record's "description" value
 * @method DmTestUser setMediaId()     Sets the current record's "media_id" value
 * @method DmTestUser setIsVisible()   Sets the current record's "is_visible" value
 * @method DmTestUser setMedia()       Sets the current record's "Media" value
 * 
 * @package    retest
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDmTestUser extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dm_test_user');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             'extra' => 'markdown',
             ));
        $this->hasColumn('media_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('is_visible', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('DmMedia as Media', array(
             'local' => 'media_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));
    }
}