<?php

/**
 * BaseDmTestComment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $dm_test_post_id
 * @property string $author
 * @property clob $body
 * @property DmTestPost $DmTestPost
 * 
 * @method integer       getDmTestPostId()    Returns the current record's "dm_test_post_id" value
 * @method string        getAuthor()          Returns the current record's "author" value
 * @method clob          getBody()            Returns the current record's "body" value
 * @method DmTestPost    getDmTestPost()      Returns the current record's "DmTestPost" value
 * @method DmTestComment setDmTestPostId()    Sets the current record's "dm_test_post_id" value
 * @method DmTestComment setAuthor()          Sets the current record's "author" value
 * @method DmTestComment setBody()            Sets the current record's "body" value
 * @method DmTestComment setDmTestPost()      Sets the current record's "DmTestPost" value
 * 
 * @package    retest
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseDmTestComment extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dm_test_comment');
        $this->hasColumn('dm_test_post_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('author', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('body', 'clob', null, array(
             'type' => 'clob',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('DmTestPost', array(
             'local' => 'dm_test_post_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $dmversionable0 = new Doctrine_Template_DmVersionable(array(
             'fields' => NULL,
             ));
        $this->actAs($timestampable0);
        $this->actAs($dmversionable0);
    }
}