<?php

/**
 * BaseDmTestPost
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $excerpt
 * @property clob $body
 * @property string $url
 * @property integer $image_id
 * @property boolean $is_active
 * @property DmMedia $Image
 * @property Doctrine_Collection $Tags
 * @property Doctrine_Collection $DmTestPostTag
 * @property Doctrine_Collection $Comments
 * 
 * @method string              getTitle()         Returns the current record's "title" value
 * @method string              getExcerpt()       Returns the current record's "excerpt" value
 * @method clob                getBody()          Returns the current record's "body" value
 * @method string              getUrl()           Returns the current record's "url" value
 * @method integer             getImageId()       Returns the current record's "image_id" value
 * @method boolean             getIsActive()      Returns the current record's "is_active" value
 * @method DmMedia             getImage()         Returns the current record's "Image" value
 * @method Doctrine_Collection getTags()          Returns the current record's "Tags" collection
 * @method Doctrine_Collection getDmTestPostTag() Returns the current record's "DmTestPostTag" collection
 * @method Doctrine_Collection getComments()      Returns the current record's "Comments" collection
 * @method DmTestPost          setTitle()         Sets the current record's "title" value
 * @method DmTestPost          setExcerpt()       Sets the current record's "excerpt" value
 * @method DmTestPost          setBody()          Sets the current record's "body" value
 * @method DmTestPost          setUrl()           Sets the current record's "url" value
 * @method DmTestPost          setImageId()       Sets the current record's "image_id" value
 * @method DmTestPost          setIsActive()      Sets the current record's "is_active" value
 * @method DmTestPost          setImage()         Sets the current record's "Image" value
 * @method DmTestPost          setTags()          Sets the current record's "Tags" collection
 * @method DmTestPost          setDmTestPostTag() Sets the current record's "DmTestPostTag" collection
 * @method DmTestPost          setComments()      Sets the current record's "Comments" collection
 * 
 * @package    retest
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseDmTestPost extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dm_test_post');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('excerpt', 'string', 800, array(
             'type' => 'string',
             'length' => '800',
             ));
        $this->hasColumn('body', 'clob', null, array(
             'type' => 'clob',
             'extra' => 'markdown',
             ));
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'extra' => 'link',
             'length' => '255',
             ));
        $this->hasColumn('image_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('DmMedia as Image', array(
             'local' => 'image_id',
             'foreign' => 'id'));

        $this->hasMany('DmTestTag as Tags', array(
             'refClass' => 'DmTestPostTag',
             'local' => 'dm_test_post_id',
             'foreign' => 'dm_test_tag_id'));

        $this->hasMany('DmTestPostTag', array(
             'local' => 'id',
             'foreign' => 'dm_test_post_id'));

        $this->hasMany('DmTestComment as Comments', array(
             'local' => 'id',
             'foreign' => 'dm_test_post_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sortable0 = new Doctrine_Template_Sortable();
        $dmgallery0 = new Doctrine_Template_DmGallery();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'title',
              1 => 'excerpt',
              2 => 'body',
              3 => 'url',
             ),
             ));
        $dmversionable1 = new Doctrine_Template_DmVersionable(array(
             'fields' => NULL,
             ));
        $i18n0->addChild($dmversionable1);
        $this->actAs($timestampable0);
        $this->actAs($sortable0);
        $this->actAs($dmgallery0);
        $this->actAs($i18n0);
    }
}