<?php

/**
 * PluginDmAutoSeo
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5845 2009-06-09 07:36:57Z jwage $
 */
abstract class PluginDmAutoSeo extends BaseDmAutoSeo
{
  public function __toString()
  {
    return sprintf('DmAutoSeo #%d %s.%s',
      $this->getId(),
      $this->getModule(),
      $this->getAction()
    );
  }
}