<?php

/**
 * DmTag
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    retest
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
class DmTag extends PluginDmTag
{
}
