<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfGuardUserPermissionTable extends myDoctrineTable
{

  public function getSortColumnName()
  {
    return 'name';
  }

}