<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginsfGuardPermission extends BasesfGuardPermission
{

  public function __toString()
  {
    return $this->get('description');
  }

}