<?php

/**
 * PluginDmSetting
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5925 2009-06-22 21:27:17Z jwage $
 */
abstract class PluginDmSetting extends BaseDmSetting
{
  
  public function preInsert($event)
  {
    parent::preInsert($event);
    
    if(!$this->value && $this->default_value)
    {
      $this->value = $this->default_value;
    }
  }

  // Get a value from the options array
  public function getOption($name, $required = false)
  {
    $config = $this->optionsArray;
    
    if ($required && !isset($config[$name])) 
    {
      throw new sfException(sprintf('Missing required option "%s" in setting %s', $name, $this->name));
    }
    
    return isset($config[$name]) ? $config[$name] : false;
  }
  
  // convert the options text area to an array
  public function getOptionsArray()
  {
    return sfToolkit::stringToArray($this->options);
  }
}