<?php

/**
 * PluginDmSetting
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5925 2009-06-22 21:27:17Z jwage $
 */
abstract class PluginDmSetting extends BaseDmSetting
{

  public function preInsert($event)
  {
    parent::preInsert($event);
    
    if(!$this->value && $this->default_value)
    {
      $this->value = $this->default_value;
    }
  }
  
}