<?php

/**
 * PluginDmCatalogue
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6716 2009-11-12 19:26:28Z jwage $
 */
abstract class PluginDmCatalogue extends BaseDmCatalogue
{

	/**
	 * @param string $source 
	 * @return boolean
	 */
  public function hasTranslationFor($source)
  {
    return dmDb::query('DmTransUnit')
    ->where('cat_id = ?', $this->get('id'))
    ->andWhere('source = ?', $source)
    ->exists();
  }
}