<?php

/**
 * PluginCatalogue
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5845 2009-06-09 07:36:57Z jwage $
 */
abstract class PluginCatalogue extends BaseCatalogue
{

  public function __toString()
  {
    return $this->getName();
  }

  public function hasTranslationFor($source)
  {
    return dmDb::query('TransUnit')
    ->where('cat_id = ? AND source = ?', array($this->cat_id, $source))
    ->exists();
  }

  public function save(Doctrine_Connection $conn = null)
  {
    if (!$this->date_created)
    {
      $this->date_created = time();
    }
    $this->date_modified = time();

    return parent::save($conn);
  }
}