<?php

/**
 * PluginDmMailTemplate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6670 2009-11-04 19:52:45Z jwage $
 */
abstract class PluginDmMailTemplate extends BaseDmMailTemplate
{

}