<?php

/**
 * PluginDmPageView
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5845 2009-06-09 07:36:57Z jwage $
 */
abstract class PluginDmPageView extends BaseDmPageView
{
  
  public function getLayout()
  {
    if (!$layout = $this->_get('Layout'))
    {
      $layout = dmDb::table('DmLayout')->findFirstOrCreate();
      $this->set('Layout', $layout);
      $this->save();
    }
    
    return $layout;
  }

  public function getArea($type)
  {
    foreach($this->get('Areas') as $area)
    {
      if($area->get('type') == $type)
      {
        return $area;
      }
    }

    $area = dmDb::create('DmArea', array(
      'dm_page_view_id' => $this->get('id'),
      'type' => $type
    ))->saveGet();

    $this->get('Areas')->add($area);

    return $area;
  }

  public function postDelete($event)
  {
    parent::postDelete($event);

    $this->Areas->delete();
  }

}