<?php

/**
 * PluginDmArea
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5845 2009-06-09 07:36:57Z jwage $
 */
abstract class PluginDmArea extends BaseDmArea
{

  # TODO more precise permissions
  public function isEditable()
  {
    if (!$sc = $this->getServiceContainer())
    {
      return false;
    }
    
    return $sc->getService('user')->can('zone_add');
  }

  public function __toString()
  {
    return sprintf('#%d %s', $this->get('id'), $this->get('type'));
  }
  
  public function save(Doctrine_Connection $conn = null)
  {
    $wasNew = $this->isNew();
    
    $return = parent::save($conn);
    
    if ($wasNew && !$this->get('Zones')->count())
    {
      dmDb::create('DmZone', array(
        'dm_area_id' => $this->get('id')
      ))->save();
      
      $this->refresh(true);
    }
  }

}