<?php

/**
 * PluginDmRedirect
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5845 2009-06-09 07:36:57Z jwage $
 */
abstract class PluginDmRedirect extends BaseDmRedirect
{
  
  public function preSave($event)
  {
    parent::preSave($event);
    
    $this->source = trim($this->get('source'), ' /');
  }
  
}