<?php

/**
 * BaseDmPermission
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $description
 * @property Doctrine_Collection $Users
 * @property Doctrine_Collection $Groups
 * @property Doctrine_Collection $DmGroupPermission
 * @property Doctrine_Collection $DmUserPermission
 * 
 * @method string              getName()              Returns the current record's "name" value
 * @method string              getDescription()       Returns the current record's "description" value
 * @method Doctrine_Collection getUsers()             Returns the current record's "Users" collection
 * @method Doctrine_Collection getGroups()            Returns the current record's "Groups" collection
 * @method Doctrine_Collection getDmGroupPermission() Returns the current record's "DmGroupPermission" collection
 * @method Doctrine_Collection getDmUserPermission()  Returns the current record's "DmUserPermission" collection
 * @method DmPermission        setName()              Sets the current record's "name" value
 * @method DmPermission        setDescription()       Sets the current record's "description" value
 * @method DmPermission        setUsers()             Sets the current record's "Users" collection
 * @method DmPermission        setGroups()            Sets the current record's "Groups" collection
 * @method DmPermission        setDmGroupPermission() Sets the current record's "DmGroupPermission" collection
 * @method DmPermission        setDmUserPermission()  Sets the current record's "DmUserPermission" collection
 * 
 * @package    retest
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseDmPermission extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dm_permission');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'length' => '255',
             ));
        $this->hasColumn('description', 'string', 5000, array(
             'type' => 'string',
             'length' => '5000',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('DmUser as Users', array(
             'refClass' => 'DmUserPermission',
             'local' => 'dm_permission_id',
             'foreign' => 'dm_user_id'));

        $this->hasMany('DmGroup as Groups', array(
             'refClass' => 'DmGroupPermission',
             'local' => 'dm_permission_id',
             'foreign' => 'dm_group_id'));

        $this->hasMany('DmGroupPermission', array(
             'local' => 'id',
             'foreign' => 'dm_permission_id'));

        $this->hasMany('DmUserPermission', array(
             'local' => 'id',
             'foreign' => 'dm_permission_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}