<?php

/**
 * BaseDmRecordPermissionUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $dm_user_id
 * @property integer $dm_record_permission_id
 * @property DmUser $User
 * @property DmRecordPermission $Record
 * 
 * @method integer                getDmUserId()                Returns the current record's "dm_user_id" value
 * @method integer                getDmRecordPermissionId()    Returns the current record's "dm_record_permission_id" value
 * @method DmUser                 getUser()                    Returns the current record's "User" value
 * @method DmRecordPermission     getRecord()                  Returns the current record's "Record" value
 * @method DmRecordPermissionUser setDmUserId()                Sets the current record's "dm_user_id" value
 * @method DmRecordPermissionUser setDmRecordPermissionId()    Sets the current record's "dm_record_permission_id" value
 * @method DmRecordPermissionUser setUser()                    Sets the current record's "User" value
 * @method DmRecordPermissionUser setRecord()                  Sets the current record's "Record" value
 * 
 * @package    retest
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDmRecordPermissionUser extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dm_record_permission_user');
        $this->hasColumn('dm_user_id', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 11,
             ));
        $this->hasColumn('dm_record_permission_id', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 11,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('DmUser as User', array(
             'local' => 'dm_user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('DmRecordPermission as Record', array(
             'local' => 'dm_record_permission_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}