<?php

/**
 * BaseDmRecordPermissionAssociationGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $dm_group_id
 * @property integer $dm_record_permission_association_id
 * @property DmRecordPermissionAssociation $Association
 * @property DmGroup $Group
 * 
 * @method integer                            getDmGroupId()                           Returns the current record's "dm_group_id" value
 * @method integer                            getDmRecordPermissionAssociationId()     Returns the current record's "dm_record_permission_association_id" value
 * @method DmRecordPermissionAssociation      getAssociation()                         Returns the current record's "Association" value
 * @method DmGroup                            getGroup()                               Returns the current record's "Group" value
 * @method DmRecordPermissionAssociationGroup setDmGroupId()                           Sets the current record's "dm_group_id" value
 * @method DmRecordPermissionAssociationGroup setDmRecordPermissionAssociationId()     Sets the current record's "dm_record_permission_association_id" value
 * @method DmRecordPermissionAssociationGroup setAssociation()                         Sets the current record's "Association" value
 * @method DmRecordPermissionAssociationGroup setGroup()                               Sets the current record's "Group" value
 * 
 * @package    retest
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDmRecordPermissionAssociationGroup extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dm_record_permission_association_group');
        $this->hasColumn('dm_group_id', 'integer', 11, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 11,
             ));
        $this->hasColumn('dm_record_permission_association_id', 'integer', 11, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 11,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('DmRecordPermissionAssociation as Association', array(
             'local' => 'dm_record_permission_association_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('DmGroup as Group', array(
             'local' => 'dm_group_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}