<?php

/**
 * BaseDmArea
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $Zones
 * 
 * @method string              getName()  Returns the current record's "name" value
 * @method Doctrine_Collection getZones() Returns the current record's "Zones" collection
 * @method DmArea              setName()  Sets the current record's "name" value
 * @method DmArea              setZones() Sets the current record's "Zones" collection
 * 
 * @package    retest
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDmArea extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dm_area');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('DmZone as Zones', array(
             'local' => 'id',
             'foreign' => 'dm_area_id'));
    }
}