<?php

/**
 * BaseDmError
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $klass
 * @property string $name
 * @property string $description
 * @property string $module
 * @property string $action
 * @property string $uri
 * @property string $env
 * 
 * @method string  getKlass()       Returns the current record's "klass" value
 * @method string  getName()        Returns the current record's "name" value
 * @method string  getDescription() Returns the current record's "description" value
 * @method string  getModule()      Returns the current record's "module" value
 * @method string  getAction()      Returns the current record's "action" value
 * @method string  getUri()         Returns the current record's "uri" value
 * @method string  getEnv()         Returns the current record's "env" value
 * @method DmError setKlass()       Sets the current record's "klass" value
 * @method DmError setName()        Sets the current record's "name" value
 * @method DmError setDescription() Sets the current record's "description" value
 * @method DmError setModule()      Sets the current record's "module" value
 * @method DmError setAction()      Sets the current record's "action" value
 * @method DmError setUri()         Sets the current record's "uri" value
 * @method DmError setEnv()         Sets the current record's "env" value
 * 
 * @package    retest
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
abstract class BaseDmError extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dm_error');
        $this->hasColumn('klass', 'string', 127, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '127',
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('description', 'string', 60000, array(
             'type' => 'string',
             'length' => '60000',
             ));
        $this->hasColumn('module', 'string', 127, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '127',
             ));
        $this->hasColumn('action', 'string', 127, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '127',
             ));
        $this->hasColumn('uri', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('env', 'string', 63, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '63',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'updated' => 
             array(
              'disabled' => true,
             ),
             ));
        $this->actAs($timestampable0);
    }
}