<?php

/**
 * BaseDmLayout
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $template
 * @property string $css_class
 * @property Doctrine_Collection $PageViews
 * @property Doctrine_Collection $Areas
 * 
 * @method string              getName()      Returns the current record's "name" value
 * @method string              getTemplate()  Returns the current record's "template" value
 * @method string              getCssClass()  Returns the current record's "css_class" value
 * @method Doctrine_Collection getPageViews() Returns the current record's "PageViews" collection
 * @method Doctrine_Collection getAreas()     Returns the current record's "Areas" collection
 * @method DmLayout            setName()      Sets the current record's "name" value
 * @method DmLayout            setTemplate()  Sets the current record's "template" value
 * @method DmLayout            setCssClass()  Sets the current record's "css_class" value
 * @method DmLayout            setPageViews() Sets the current record's "PageViews" collection
 * @method DmLayout            setAreas()     Sets the current record's "Areas" collection
 * 
 * @package    retest
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDmLayout extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dm_layout');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('template', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'page',
             'length' => 255,
             ));
        $this->hasColumn('css_class', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('DmPageView as PageViews', array(
             'local' => 'id',
             'foreign' => 'dm_layout_id'));

        $this->hasMany('DmArea as Areas', array(
             'local' => 'id',
             'foreign' => 'dm_layout_id'));
    }
}