<?php

/**
 * BaseDmError
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $php_class
 * @property string $name
 * @property string $description
 * @property string $module
 * @property string $action
 * @property string $uri
 * @property string $env
 * 
 * @method string  getPhpClass()    Returns the current record's "php_class" value
 * @method string  getName()        Returns the current record's "name" value
 * @method string  getDescription() Returns the current record's "description" value
 * @method string  getModule()      Returns the current record's "module" value
 * @method string  getAction()      Returns the current record's "action" value
 * @method string  getUri()         Returns the current record's "uri" value
 * @method string  getEnv()         Returns the current record's "env" value
 * @method DmError setPhpClass()    Sets the current record's "php_class" value
 * @method DmError setName()        Sets the current record's "name" value
 * @method DmError setDescription() Sets the current record's "description" value
 * @method DmError setModule()      Sets the current record's "module" value
 * @method DmError setAction()      Sets the current record's "action" value
 * @method DmError setUri()         Sets the current record's "uri" value
 * @method DmError setEnv()         Sets the current record's "env" value
 * 
 * @package    retest
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDmError extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dm_error');
        $this->hasColumn('php_class', 'string', 127, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 127,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 60000, array(
             'type' => 'string',
             'length' => 60000,
             ));
        $this->hasColumn('module', 'string', 127, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 127,
             ));
        $this->hasColumn('action', 'string', 127, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 127,
             ));
        $this->hasColumn('uri', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('env', 'string', 63, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 63,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'updated' => 
             array(
              'disabled' => true,
             ),
             ));
        $this->actAs($timestampable0);
    }
}