<?php

/**
 * BaseDmMailTemplate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $description
 * @property string $vars
 * @property string $title
 * @property clob $body
 * @property string $from_email
 * @property string $to_email
 * @property boolean $is_html
 * @property boolean $is_active
 * 
 * @method string         getName()        Returns the current record's "name" value
 * @method string         getDescription() Returns the current record's "description" value
 * @method string         getVars()        Returns the current record's "vars" value
 * @method string         getTitle()       Returns the current record's "title" value
 * @method clob           getBody()        Returns the current record's "body" value
 * @method string         getFromEmail()   Returns the current record's "from_email" value
 * @method string         getToEmail()     Returns the current record's "to_email" value
 * @method boolean        getIsHtml()      Returns the current record's "is_html" value
 * @method boolean        getIsActive()    Returns the current record's "is_active" value
 * @method DmMailTemplate setName()        Sets the current record's "name" value
 * @method DmMailTemplate setDescription() Sets the current record's "description" value
 * @method DmMailTemplate setVars()        Sets the current record's "vars" value
 * @method DmMailTemplate setTitle()       Sets the current record's "title" value
 * @method DmMailTemplate setBody()        Sets the current record's "body" value
 * @method DmMailTemplate setFromEmail()   Sets the current record's "from_email" value
 * @method DmMailTemplate setToEmail()     Sets the current record's "to_email" value
 * @method DmMailTemplate setIsHtml()      Sets the current record's "is_html" value
 * @method DmMailTemplate setIsActive()    Sets the current record's "is_active" value
 * 
 * @package    retest
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseDmMailTemplate extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dm_mail_template');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => '255',
             ));
        $this->hasColumn('description', 'string', 5000, array(
             'type' => 'string',
             'length' => '5000',
             ));
        $this->hasColumn('vars', 'string', 5000, array(
             'type' => 'string',
             'length' => '5000',
             ));
        $this->hasColumn('title', 'string', 5000, array(
             'type' => 'string',
             'length' => '5000',
             ));
        $this->hasColumn('body', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('from_email', 'string', 5000, array(
             'type' => 'string',
             'length' => '5000',
             ));
        $this->hasColumn('to_email', 'string', 5000, array(
             'type' => 'string',
             'length' => '5000',
             ));
        $this->hasColumn('is_html', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'title',
              1 => 'description',
              2 => 'body',
              3 => 'from_email',
              4 => 'to_email',
              5 => 'is_html',
              6 => 'is_active',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($i18n0);
    }
}