<?php

/**
 * BaseDmWidget
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $dm_zone_id
 * @property string $module
 * @property string $action
 * @property string $value
 * @property string $css_class
 * @property DmZone $Zone
 * 
 * @method integer  getDmZoneId()   Returns the current record's "dm_zone_id" value
 * @method string   getModule()     Returns the current record's "module" value
 * @method string   getAction()     Returns the current record's "action" value
 * @method string   getValue()      Returns the current record's "value" value
 * @method string   getCssClass()   Returns the current record's "css_class" value
 * @method DmZone   getZone()       Returns the current record's "Zone" value
 * @method DmWidget setDmZoneId()   Sets the current record's "dm_zone_id" value
 * @method DmWidget setModule()     Sets the current record's "module" value
 * @method DmWidget setAction()     Sets the current record's "action" value
 * @method DmWidget setValue()      Sets the current record's "value" value
 * @method DmWidget setCssClass()   Sets the current record's "css_class" value
 * @method DmWidget setZone()       Sets the current record's "Zone" value
 * 
 * @package    retest
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDmWidget extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dm_widget');
        $this->hasColumn('dm_zone_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('module', 'string', 127, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 127,
             ));
        $this->hasColumn('action', 'string', 127, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 127,
             ));
        $this->hasColumn('value', 'string', 60000, array(
             'type' => 'string',
             'length' => 60000,
             ));
        $this->hasColumn('css_class', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('DmZone as Zone', array(
             'local' => 'dm_zone_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $sortable0 = new Doctrine_Template_Sortable(array(
             ));
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'created' => 
             array(
              'disabled' => true,
             ),
             ));
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'value',
             ),
             'length' => 7,
             ));
        $this->actAs($sortable0);
        $this->actAs($timestampable0);
        $this->actAs($i18n0);
    }
}