<?php

/**
 * PluginDmRecordPermissionGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDmRecordPermissionGroupTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginDmRecordPermissionGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginDmRecordPermissionGroup');
    }
}