<?php

/**
 * PluginDmRecordPermissionUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDmRecordPermissionUserTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginDmRecordPermissionUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginDmRecordPermissionUser');
    }
}