<?php

/**
 * PluginDmRecordPermissionAssociationGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDmRecordPermissionAssociationGroupTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginDmRecordPermissionAssociationGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginDmRecordPermissionAssociationGroup');
    }
}