<?php

/**
 * PluginDmRecordPermissionAssociationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDmRecordPermissionAssociationTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginDmRecordPermissionAssociationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginDmRecordPermissionAssociation');
    }
}