<?php

/**
 * PluginDmRecordPermission
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginDmRecordPermission extends BaseDmRecordPermission
{
  public function __toString()
  {
    return $this->get('description');
  }
  
  public function getRecord()
  {
    $table = Doctrine_Core::getTable($this->get('secure_model')); 
    return $table->findOneBy($table->getIdentifier(), $this->get('secure_record'));
  }
  
  public function postInsert($event)
  {
  	$this->getService('record_permission_association_manager')->manage($this);
  }
}