<?php

/**
 * PluginDmProfile
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5845 2009-06-09 07:36:57Z jwage $
 */
abstract class PluginDmProfile extends BaseDmProfile
{
  
  public function __toString()
  {
    return $this->User->__toString();
  }
  
  public function getUsername()
  {
    return $this->User->username;
  }
  
  public function getEmail()
  {
    return $this->User->email;
  }
  
  public function getLastLogin()
  {
    return $this->User->lastLogin;
  }
}